dirstructure support

diff --git a/build/alpine/gitd/git-shell-commands/new b/build/alpine/gitd/git-shell-commands/new
--- a/build/alpine/gitd/git-shell-commands/new
+++ b/build/alpine/gitd/git-shell-commands/new
@@ -1,29 +1,28 @@
 #!/bin/sh -e
 
+function valid() {
+  echo "$1" | grep -E '[[:alnum:]]+(/[[:alnum:]]+)*'
+}
+
 function new() {
   if test -z "$1"; then
     echo "Usage: new REPOPATH"
     exit 1
   fi
 
-  local repo_path="${GIT_ROOT:-git}/$1"
-
-  repo_path="${repo_path%.git}"
-  repo_path="${repo_path%/}"
-
-  if echo "$repo_path" | grep -q "\.git"; then
-    echo invalid name
-    exir 2
+  if ! valid "$1"; then
+    echo "Invalid path"
+    exit 2
   fi
 
-  repo_path="${repo_path}.git"
+  local repo_path="${GIT_ROOT:-git}/$1.git"
 
   if test -e "$repo_path"; then
     echo "This repository already exists"
     exit 3
   fi
 
-  mkdir "${repo_path}"
+  mkdir -p "${repo_path}"
   cd "${repo_path}"
   git init --bare
 
